name = "darwin-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Bind to KV Namespace for Genome Storage
# Run `wrangler kv:namespace create GENOME` to get ID
kv_namespaces = [
  { binding = "GENOME", id = "REPLACE_WITH_REAL_ID" }
]
